name: Code Review
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Code review
        uses: ai-action/pull-request-review@v1
